import { IsString, IsOptional, IsEnum, IsDateString, IsArray, IsNumber, IsUUID, IsBoolean, MinLength } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { ProjectStatus, ProjectBillingType, ProjectPaymentStatus } from '../project.entity';
import { PartialType } from '@nestjs/mapped-types';

export class CreateProjectDto {
  @ApiProperty() @IsString() @MinLength(1) name: string;
  @ApiProperty({ required: false }) @IsOptional() @IsString() description?: string;
  @ApiProperty({ required: false }) @IsOptional() @IsUUID() managerId?: string;
  @ApiProperty({ required: false }) @IsOptional() @IsDateString() startDate?: string;
  @ApiProperty({ required: false }) @IsOptional() @IsDateString() endDate?: string;
  @ApiProperty({ enum: ProjectStatus, required: false }) @IsOptional() @IsEnum(ProjectStatus) status?: ProjectStatus;
  @ApiProperty({ required: false }) @IsOptional() @IsString() color?: string;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() budget?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() paidAmount?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsString() salesManagerId?: string;
  @ApiProperty({ required: false, type: [String] }) @IsOptional() @IsArray() memberIds?: string[];
  @ApiProperty({ required: false }) @IsOptional() @IsString() projectType?: string;
  @ApiProperty({ required: false }) @IsOptional() smmData?: Record<string, any>;
  @ApiProperty({ required: false }) @IsOptional() clientInfo?: Record<string, any>;

  // ─── Tariff & billing (Wave 2) ─────────────────────────────────────
  @ApiProperty({ required: false }) @IsOptional() @IsUUID() tariffId?: string;
  @ApiProperty({ enum: ProjectBillingType, required: false }) @IsOptional() @IsEnum(ProjectBillingType) billingType?: ProjectBillingType;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() monthlyFee?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsDateString() startBillingDate?: string;
  @ApiProperty({ required: false }) @IsOptional() @IsDateString() nextPaymentDate?: string;
  @ApiProperty({ enum: ProjectPaymentStatus, required: false }) @IsOptional() @IsEnum(ProjectPaymentStatus) paymentStatus?: ProjectPaymentStatus;
  @ApiProperty({ required: false }) @IsOptional() @IsBoolean() isAutoGeneratedFromTariff?: boolean;

  // ─── Wave 13: финансы (TZ п.10) ────────────────────────────────────
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() totalContractValue?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() outstandingAmount?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() internalCostEstimate?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() marginEstimate?: number;
  @ApiProperty({ required: false }) @IsOptional() @IsNumber() tariffLimitOveruseCost?: number;
}

export class UpdateProjectDto extends PartialType(CreateProjectDto) {}
