import {
  Entity, PrimaryGeneratedColumn, Column, CreateDateColumn,
  UpdateDateColumn, ManyToOne, OneToMany, ManyToMany, JoinTable, JoinColumn,
} from 'typeorm';
import { User } from '../users/user.entity';
import { Task } from '../tasks/task.entity';
import { FileAttachment } from '../files/file.entity';

export enum ProjectStatus {
  PLANNING = 'planning',
  IN_PROGRESS = 'in_progress',
  COMPLETED = 'completed',
  ARCHIVED = 'archived',
  ON_HOLD = 'on_hold',
}

/** Биллинговая модель проекта.
 *  - one_time   — разовая оплата за проект (сайты, разработка)
 *  - monthly    — ежемесячная подписка (SMM-тарифы)
 *  - recurring  — повторяющаяся, но не помесячная (каждые N дней)
 */
export enum ProjectBillingType {
  ONE_TIME  = 'one_time',
  MONTHLY   = 'monthly',
  RECURRING = 'recurring',
}

/** Состояние оплаты проекта (используется в финансовой аналитике). */
export enum ProjectPaymentStatus {
  PENDING         = 'pending',
  INVOICE_SENT    = 'invoice_sent',
  PARTIALLY_PAID  = 'partially_paid',
  PAID            = 'paid',
  OVERDUE         = 'overdue',
  FROZEN          = 'frozen',
}

@Entity('projects')
export class Project {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column()
  name: string;

  @Column({ type: 'text', nullable: true })
  description: string;

  @ManyToOne(() => User, { nullable: true, eager: true })
  @JoinColumn()
  manager: User;

  @Column({ nullable: true })
  managerId: string;

  @Column({ type: 'date', nullable: true })
  startDate: Date;

  @Column({ type: 'date', nullable: true })
  endDate: Date;

  @Column({ type: 'enum', enum: ProjectStatus, default: ProjectStatus.PLANNING })
  status: ProjectStatus;

  @Column({ nullable: true })
  color: string;

  @Column({ nullable: true })
  budget: number;

  @Column({ nullable: true, type: 'decimal', precision: 15, scale: 2 })
  paidAmount: number;

  @Column({ nullable: true })
  salesManagerId: string;

  @ManyToOne(() => User, { nullable: true, eager: true })
  @JoinColumn({ name: 'salesManagerId' })
  salesManager: User;

  @Column({ default: 0 })
  progress: number;

  @ManyToMany(() => User, { eager: true })
  @JoinTable({ name: 'project_members' })
  members: User[];

  @OneToMany(() => Task, task => task.project)
  tasks: Task[];

  @OneToMany(() => FileAttachment, file => file.project)
  files: FileAttachment[];

  @Column({ nullable: true })
  projectType: string;

  @Column({ type: 'jsonb', nullable: true })
  smmData: Record<string, any>;

  @Column({ type: 'jsonb', nullable: true })
  clientInfo: Record<string, any>;

  @Column({ default: false })
  isArchived: boolean;

  // ─── Tariff & billing (Wave 2: SMM tariffs integration) ──────────────
  /** FK на smm_tariffs.id. Заполняется только для SMM-проектов. */
  @Column({ nullable: true })
  tariffId: string;

  /** Снимок имени тарифа на момент привязки — чтобы переименование/удаление
   *  тарифа не ломало историю проектов. */
  @Column({ nullable: true })
  tariffNameSnapshot: string;

  /** Снимок цены тарифа на момент привязки. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  tariffPriceSnapshot: number;

  @Column({ type: 'enum', enum: ProjectBillingType, nullable: true })
  billingType: ProjectBillingType;

  /** Ежемесячная плата (для monthly billing). Может отличаться от
   *  tariffPriceSnapshot — индивидуальная скидка/наценка для клиента. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  monthlyFee: number;

  @Column({ type: 'date', nullable: true })
  startBillingDate: Date;

  @Column({ type: 'date', nullable: true })
  nextPaymentDate: Date;

  @Column({ type: 'enum', enum: ProjectPaymentStatus, default: ProjectPaymentStatus.PENDING })
  paymentStatus: ProjectPaymentStatus;

  /** Признак: проект сгенерирован из шаблона тарифа (контент-план,
   *  стартовые задачи). Нужен чтобы повторно не пересоздавать. */
  @Column({ default: false })
  isAutoGeneratedFromTariff: boolean;

  // ─── Wave 13: Финансы и прибыльность (TZ п.10) ───────────────────────
  /** Полная стоимость контракта (для проектных одноразовых работ).
   *  Для SMM с тарифом — обычно сумма за период обслуживания. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  totalContractValue: number;

  /** Остаток к оплате = totalContractValue − paidAmount. Авто-пересчёт
   *  при изменении total/paid. Хранится для быстрых выборок и алертов. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  outstandingAmount: number;

  /** Внутренняя стоимость проекта для агентства (зарплаты, продакшн, реклама). */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  internalCostEstimate: number;

  /** Маржа = totalContractValue − internalCostEstimate. Авто-пересчёт. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  marginEstimate: number;

  /** Денежная оценка перерасхода по лимитам тарифа.
   *  Авто-пересчёт: для каждого превышенного типа контента берётся
   *  средняя стоимость единицы (monthlyPrice / sum_of_planned_units)
   *  и умножается на overuse. Можно перебить вручную. */
  @Column({ type: 'decimal', precision: 15, scale: 2, nullable: true })
  tariffLimitOveruseCost: number;

  // ─── Wave 7: Launch Setup checklist ─────────────────────────────────
  /** Состояние launch-чеклиста проекта. Хранит ТОЛЬКО ручные пункты
   *  (materials_received, accesses_received). Остальные 8 пунктов
   *  вычисляются на лету из связанных данных (тариф, менеджер, members,
   *  задачи, контент-план, оплата). Структура: { [key]: boolean }. */
  @Column({ type: 'jsonb', nullable: true, default: () => `'{}'::jsonb` })
  launchChecklist: Record<string, boolean>;

  @CreateDateColumn()
  createdAt: Date;

  @UpdateDateColumn()
  updatedAt: Date;
}
