import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddProjectTariffIntegration1746100000000 implements MigrationInterface {
  name = 'AddProjectTariffIntegration1746100000000';

  async up(queryRunner: QueryRunner): Promise<void> {
    // Enums
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "projects_billing_type_enum" AS ENUM ('one_time', 'monthly', 'recurring');
      EXCEPTION WHEN duplicate_object THEN null; END $$;
    `);
    await queryRunner.query(`
      DO $$ BEGIN
        CREATE TYPE "projects_payment_status_enum" AS ENUM (
          'pending', 'invoice_sent', 'partially_paid', 'paid', 'overdue', 'frozen'
        );
      EXCEPTION WHEN duplicate_object THEN null; END $$;
    `);

    // Columns (additive — старые проекты получают NULL/дефолты)
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tariffId" uuid NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tariffNameSnapshot" varchar NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "tariffPriceSnapshot" DECIMAL(15, 2) NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "billingType" "projects_billing_type_enum" NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "monthlyFee" DECIMAL(15, 2) NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "startBillingDate" DATE NULL`);
    await queryRunner.query(`ALTER TABLE "projects" ADD COLUMN IF NOT EXISTS "nextPaymentDate" DATE NULL`);
    await queryRunner.query(`
      ALTER TABLE "projects"
      ADD COLUMN IF NOT EXISTS "paymentStatus" "projects_payment_status_enum" NOT NULL DEFAULT 'pending'
    `);
    await queryRunner.query(`
      ALTER TABLE "projects"
      ADD COLUMN IF NOT EXISTS "isAutoGeneratedFromTariff" boolean NOT NULL DEFAULT false
    `);

    // FK to smm_tariffs (опциональная связь, ON DELETE SET NULL — снимок остаётся)
    await queryRunner.query(`
      DO $$ BEGIN
        ALTER TABLE "projects"
        ADD CONSTRAINT "FK_projects_tariff"
        FOREIGN KEY ("tariffId") REFERENCES "smm_tariffs"("id") ON DELETE SET NULL;
      EXCEPTION WHEN duplicate_object THEN null; END $$;
    `);

    // Индексы для аналитики (фильтры по статусу оплаты, по дате следующего платежа)
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_projects_payment_status" ON "projects" ("paymentStatus")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_projects_next_payment" ON "projects" ("nextPaymentDate")`);
    await queryRunner.query(`CREATE INDEX IF NOT EXISTS "IDX_projects_tariff" ON "projects" ("tariffId")`);
  }

  async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_projects_tariff"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_projects_next_payment"`);
    await queryRunner.query(`DROP INDEX IF EXISTS "IDX_projects_payment_status"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT IF EXISTS "FK_projects_tariff"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "isAutoGeneratedFromTariff"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "paymentStatus"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "nextPaymentDate"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "startBillingDate"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "monthlyFee"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "billingType"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "tariffPriceSnapshot"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "tariffNameSnapshot"`);
    await queryRunner.query(`ALTER TABLE "projects" DROP COLUMN IF EXISTS "tariffId"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "projects_payment_status_enum"`);
    await queryRunner.query(`DROP TYPE IF EXISTS "projects_billing_type_enum"`);
  }
}
